# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 353)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lbl_protocalType = QtWidgets.QLabel(self.centralWidget)
        self.lbl_protocalType.setGeometry(QtCore.QRect(20, 40, 59, 16))
        self.lbl_protocalType.setObjectName("lbl_protocalType")
        self.lbl_protocalData = QtWidgets.QLabel(self.centralWidget)
        self.lbl_protocalData.setGeometry(QtCore.QRect(20, 80, 59, 16))
        self.lbl_protocalData.setObjectName("lbl_protocalData")
        self.pbtn_Analysis = QtWidgets.QPushButton(self.centralWidget)
        self.pbtn_Analysis.setGeometry(QtCore.QRect(150, 278, 141, 35))
        self.pbtn_Analysis.setObjectName("pbtn_Analysis")
        self.cmbx_protocalType = QtWidgets.QComboBox(self.centralWidget)
        self.cmbx_protocalType.setGeometry(QtCore.QRect(90, 35, 251, 31))
        self.cmbx_protocalType.setEditable(False)
        self.cmbx_protocalType.setObjectName("cmbx_protocalType")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.cmbx_protocalType.addItem("")
        self.txtEdt_protocalData = QtWidgets.QTextEdit(self.centralWidget)
        self.txtEdt_protocalData.setGeometry(QtCore.QRect(90, 78, 251, 191))
        self.txtEdt_protocalData.setObjectName("txtEdt_protocalData")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(350, 0, 20, 321))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnClear = QtWidgets.QPushButton(self.centralWidget)
        self.btnClear.setGeometry(QtCore.QRect(460, 278, 141, 35))
        self.btnClear.setObjectName("btnClear")
        self.txtEdt_result = QtWidgets.QTextEdit(self.centralWidget)
        self.txtEdt_result.setGeometry(QtCore.QRect(380, 39, 301, 231))
        self.txtEdt_result.setObjectName("txtEdt_result")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(370, 15, 59, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "协议解析"))
        self.lbl_protocalType.setText(_translate("MainWindow", "协议类型："))
        self.lbl_protocalData.setText(_translate("MainWindow", "协议数据："))
        self.pbtn_Analysis.setText(_translate("MainWindow", "解    析"))
        self.cmbx_protocalType.setItemText(0, _translate("MainWindow", "1826F456(CHM)"))
        self.cmbx_protocalType.setItemText(1, _translate("MainWindow", "182756F4(BHM)"))
        self.cmbx_protocalType.setItemText(2, _translate("MainWindow", "1801F456(CRM)"))
        self.cmbx_protocalType.setItemText(3, _translate("MainWindow", "BRM多包数据报文"))
        self.cmbx_protocalType.setItemText(4, _translate("MainWindow", "BCP多包数据报文"))
        self.cmbx_protocalType.setItemText(5, _translate("MainWindow", "1808F456(CML)"))
        self.cmbx_protocalType.setItemText(6, _translate("MainWindow", "100956F4(BRO)"))
        self.cmbx_protocalType.setItemText(7, _translate("MainWindow", "100AF456(CRO)"))
        self.cmbx_protocalType.setItemText(8, _translate("MainWindow", "181056F4(BCL)"))
        self.cmbx_protocalType.setItemText(9, _translate("MainWindow", "BCS多包数据报文"))
        self.cmbx_protocalType.setItemText(10, _translate("MainWindow", "1812F456(CCS)"))
        self.cmbx_protocalType.setItemText(11, _translate("MainWindow", "181356F4(BSM)"))
        self.cmbx_protocalType.setItemText(12, _translate("MainWindow", "BMV多包数据报文"))
        self.cmbx_protocalType.setItemText(13, _translate("MainWindow", "BMT多包数据报文"))
        self.cmbx_protocalType.setItemText(14, _translate("MainWindow", "101956F4(BST)"))
        self.cmbx_protocalType.setItemText(15, _translate("MainWindow", "101AF456(CST)"))
        self.cmbx_protocalType.setItemText(16, _translate("MainWindow", "181C56F4(BSD)"))
        self.cmbx_protocalType.setItemText(17, _translate("MainWindow", "181DF456(CSD)"))
        self.cmbx_protocalType.setItemText(18, _translate("MainWindow", "081E56F4(BEM)"))
        self.cmbx_protocalType.setItemText(19, _translate("MainWindow", "081FF456(CEM)"))
        self.txtEdt_protocalData.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnClear.setText(_translate("MainWindow", "清    空"))
        self.label.setText(_translate("MainWindow", "解析结果："))

